name: own-check
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
        make configure
    - name: DB preparation
      run: make migrate
    - name: Linting
      run: make lint
    - name: Testing
      run: make test
    - name: Checking coverage by Code Climate
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make cover
        coverageLocations: ./coverage.lcov:lcov
        verifyDownload: true